-- base_data
CREATE OR REPLACE TABLE `stalwart-seat-484411-v0.aqi_mlops.base_data` AS ...

-- features
CREATE OR REPLACE TABLE `stalwart-seat-484411-v0.aqi_mlops.features` AS ...

-- training_data
CREATE OR REPLACE TABLE `stalwart-seat-484411-v0.aqi_mlops.training_data` AS ...